slam_toolbox:
  ros__parameters:
    # map_update_interval: 5.0
    # resolution: 0.05
    scan_topic: /autodrive/f1tenth_1/lidar
    # use_sim_time: false
    # base_frame: base_link
    # odom_frame: odom
    # map_frame: map
    mode: asynchronous